DeveloperAcademy-POSTECH/NatureUp

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/ContentView.swift, NatureUp/Views/Market/Profile/NamePlate.swift, NatureUp/Views/Market/Profile/ProfileStatus.swift, NatureUp/Views/Market/Profile/ProfileView.swift
=> 기능 추가 : 프로필페이지

NatureUp/Views/LeaderBoard/LeaderBoardView.swift
=> 기능 수정 : 등수, 경험치 디자인 변경

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/Authentication/AuthenticationView.swift, NatureUp/Views/ContentView.swift, NatureUp/Views/Evaluation/EvaluationCompleteView.swift, NatureUp/Views/Evaluation/EvaluationView.swift
1. 인증완료 페이지 추가
2. ProgressView 기능 수정
3. 평가페이지 하단에 여백이 생겨 ignoreSafeArea 코드 추가 하였습니다
4.  평가페이지에서 카메라 촬영 후 나타나는 '인증하기'버튼 텍스트 굵기 변경하였습니다 (semibold → bold)
5. 평가페이지에서 '다른사람 평가하기' 제목 삭제하였습니다 (디자인 수정)
6. 컨텐트뷰의 네비게이션뷰에 적용되지 않았던 accentColor을 추가 하였습니다
=> 기능추가 및 버그 수정 하였습니다.

NatureUp/Views/LeaderBoard/LeaderBoardRow.swift, NatureUp/Views/LeaderBoard/LeaderBoardView.swift
=> 버그 수정 : 리더보드 수정

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/Home/activityData.json, NatureUp/Views/Market/Profile/ActivityPictureCell.swift
ProfileView에 사진 삽입한 건 이것 저것 시도해본거라 다시 코딩 할 예정입니다
=> 기능추가: 환경 활동 리스트 json파일 추가 및 ProfileView 사진 삽입

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/LeaderBoard/LeaderBoardRow.swift, NatureUp/Views/LeaderBoard/LeaderBoardView.swift, NatureUp/Views/LeaderBoard/MyLeaderBoardStatus.swift
=> 기능 수정 : 리더보드 등수, 경험치 바 고정 탭뷰 오류 추가 수정, 순위 이미지간 간격 조정

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/LeaderBoard/leaderBoard.json
리더보드에 들어갈 랭킹+이름 json파일을 생성했습니다.
=> 기타: 리더보드 json파일 생성

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/Authentication/AuthenticationSuccessView.swift, NatureUp/Views/Authentication/AuthenticationView.swift, NatureUp/Views/Home/Activity.swift, NatureUp/Views/Home/LocationListView.swift
=> 버그수정 : 네비게이션 뷰 중첩오류

NatureUp/Model/leaderBoardData.json, NatureUp/Views/LeaderBoard/LeaderBoardList.swift, NatureUp/Views/LeaderBoard/LeaderBoardRow.swift, NatureUp/Views/LeaderBoard/userRanking.swift
=> 기능수정: 리더보드 4~20위 리스트 수정 완료

NatureUp/Views/LeaderBoard/LeaderBoardView.swift
=> 기능 수정 : 리더 보드 이슈 수정(1~3순위 디자인 변경)

NatureUp.xcodeproj/project.pbxproj, NatureUp/NatureUpApp.swift
MapView에서 ContentView로 수정하였습니다
=> 버그수정: 메인화면

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/ContentView.swift, NatureUp/Views/Market/Profile/ProfileEditor.swift, NatureUp/Views/Market/Profile/ProfileView.swift
edit 버튼을 네비게이션 바로 옮기고 연결될 수 있게 하는 등의 수정 필요
=> 기능추가 및 변경: 프로필 수정 페이지를 생성, edit 버튼 위치 변경

NatureUp/Views/LeaderBoard/LeaderBoardList.swift, NatureUp/Views/LeaderBoard/LeaderBoardRow.swift, NatureUp/Views/LeaderBoard/LeaderBoardView.swift
=> 기능 수정: 리더보드 1,2,3 순위 간격조절

NatureUp/Views/LeaderBoard/LeaderBoardList.swift, NatureUp/Views/LeaderBoard/LeaderBoardView.swift
리더 보드 클릭시 앱 내의 네비게이션 바가 사라지는 오류를 수정하였습니다. 그로 인한 디자인도 함께 수정하였습니다.
해결 : #48
@DevLuce
=> 버그 수정 : 리더 보드 클릭시 네비게이션 바 사라지는 버그 수정

NatureUp/Views/ContentView.swift, NatureUp/Views/Profile/ProfileEditor.swift
도움을 준 네이스에게 무한한 감사,,,
근데 NavigationLink는 왜 적용이 안되는지 모르겠어요
=> 기능 변경: Edit 버튼을 누르면 ProfileEditor로 연결되도록 변경

NatureUp/Views/Profile/ProfileEditor.swift
=> 기능 변경: ProfileEditor창에서 Alert 버튼 구현

NatureUp/Views/Home/MyStatus.swift
=> 버그수정 : 홈뷰 status바 수정

NatureUp/Views/ContentView.swift
1. 지도보기 버튼 위치 수정
2. 알림뷰 프리젠테이션 방식 변경
=> 기능수정: 컨텐트뷰

NatureUp/Views/Home/ActivityList.swift
ActivityList에서 보여지는 레이블을 한글로 표시되게 맵핑하였습니다.
=> 기능수정 : 활동 리스트 위치 맵핑

NatureUp/Views/Market/MarketView.swift
MarketView에서 네비게이션바가 투명으로 보이는 오류를 수정하였습니다.
=> 버그수정 : MarketView 네비게이션바 수정

NatureUp/Views/Home/ActivityList.swift, NatureUp/Views/Home/ActivityRow.swift, NatureUp/Views/Home/LocationListView.swift
활동에서 포인트와 경험치를 난이도에 따라 부여하여 추가하였습니다.
=> 기능추가 : 포인트와 경험치 표시 추가

NatureUp/Views/Profile/ProfileEditor.swift
=> 기능추가 : 프로필에디터 

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/Home/HomeView.swift, NatureUp/Views/Home/LocationManager.swift
=> 기능 추가 : 사용자 위치 정보 제공

NatureUp/Resources/locations.json
=> 문서 : 위치 데이터 추가

NatureUp.xcodeproj/project.pbxproj, NatureUp/Views/Home/HomeView.swift
ScrollView 리프레시 기능을 추가하여 현재 위치를 다시 불러올 수 있도록 구현하였습니다.
=> 기능추가 : ScrollView 리프레시 기능 추가

NatureUp/Views/Evaluation/EvaluationCompleteView.swift
평가 완료 후 받는 경험치를 포인트로 보상을 받는 것으로 수정하였습니다.
=> 기능수정 : 평가 완료 보상 수정

README.md
=> 문서 : README 문서 업데이트

NatureUp/Views/Evaluation/EvaluationCompleteView.swift
=> 버그수정 : 평가완료페이지
